## Numpy

Numpy is similar to lists.

**Lists**
- Store different type of data (1, 2, 3, "we are learning python with aammar", "codanics, True).
- Much less efficient than Numpy.
- Suiteable for short codes.

**Numpy**
- Store same type of data (5, 5, 5, 5, 5, 10, 12 ,15).
- Store data very compactly.
- Suitable for big numerical operations.
- Consumse less memory and is more convenient to use.

**Array**
- A central data structure of Numpy library is called an array.
- A grid of values that contains information about the raw data, how to locate an element, and how to interpret an element.
- The elements that are of same type is reffered to as the array dtype.
- A line of students in a school assesmbly is an good example of one dimensional array.
- An array can be indexed by a tuple of non-negative integers, by booleans, by another array or integers.
- One dimesional array is known as vector. A line of students in a school assesmbly is an good example of vector.
- Two dimensional array is known as matrix, e.g., lines of students of all classes in a school assembly.
- ndarray class means "number of dimensions of array" and it represent both vector and marix. 
- For three dimensional array, the term tensor is commonly used. TensorFlow, an open source software used for ML and AI. 

For extensive study and practice: [visit the manual](https://numpy.org/doc/stable/user/absolute_beginners.html)



---

## 1-D array

In [3]:
import numpy as np
a=np.array([5, 5, 5, 5])
a

array([5, 5, 5, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
len(a)

4

In [17]:
a[0]

5

In [18]:
a[0:]

array([5, 5, 5, 5])

In [19]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [20]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [23]:
#empty array function is used to create an empty array with 2 elements.
b =np.empty(2)
b

array([7.45086745e-312, 4.94065646e-324])

In [26]:
#arange function is used to create a range of elements
c=np.arange(6)
c
d=np.arange(2,10)
d

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#continue ....
e=np.arange(2, 20, 4) #it's giving us numbers from 2-20 with the interval of 4.
e

array([ 2,  6, 10, 14, 18])

In [28]:
#Linerly spaced arrays
f=np.linspace(0,10, num=4) #it's giving us 4 numbers from 0-10 which have equall distance or line space. 
f

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [29]:
#Specific data type in an array
i=np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [31]:
#for float
j=np.ones(4, dtype=np.float64)
j

array([1., 1., 1., 1.])

## 2-D array

In [11]:
b= np.array([[5,5,5], [8,9,9], [3,4,5]])
b

array([[5, 5, 5],
       [8, 9, 9],
       [3, 4, 5]])

In [12]:
type(b)

numpy.ndarray

In [13]:
len(b)

3

In [14]:
b[0]

array([5, 5, 5])

In [16]:
b[0:]

array([[5, 5, 5],
       [8, 9, 9],
       [3, 4, 5]])

In [35]:
c=np.zeros((3, 4)) # first axis=3 and second axis= 4
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
d=np.ones((5,6))
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## 3-D array

In [38]:
#making and reshaping a 3D array
c=np.arange(24) .reshape(2, 3, 4) #2 means quantity of arrays, 3 means first axis, 4 means second axis.
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

---

## Numpy Practice

In [ ]:
import numpy as np


In [39]:
#1-D array 
food= np.array(["Pakora", "Samosa", "Raita", "Salad"])
food

array(['Pakora', 'Samosa', 'Raita', 'Salad'], dtype='<U6')

In [41]:
type(food)

numpy.ndarray

In [45]:
len(food)

4

In [47]:
food[3]

'Salad'

In [50]:
#we can print everything of an array using [0:]
food[0:]

array(['Pakora', 'Samosa', 'Raita', 'Salad'], dtype='<U6')

In [40]:
prices=np.array([30, 45, 15, 10])
prices

array([30, 45, 15, 10])

In [43]:
type(prices)

numpy.ndarray

In [44]:
len(prices)

4

In [48]:
prices[3]

10

In [51]:
prices[0:]

array([30, 45, 15, 10])

In [52]:
prices.mean()

25.0

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.empty(2)

array([0., 0.])

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [62]:
np.arange(1,14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [63]:
np.arange(0,50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [64]:
np.ones(10, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [65]:
np.ones(40, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [66]:
a=np.array([10, 15, 13, 11, 17, 0.5, 6, 8, 50, 78])
a

[10, 15, 13, 11, 17, 0.5, 6, 8, 50, 78]

In [70]:
a.sort()
a

[0.5, 6, 8, 10, 11, 13, 15, 17, 50, 78]

In [71]:
b=np.array([14, 54, 56, 78, 90, 0.4, 67, 3])
b.sort()
b

array([ 0.4,  3. , 14. , 54. , 56. , 67. , 78. , 90. ])

In [73]:
c=np.concatenate((a,b))
c

array([ 0.5,  6. ,  8. , 10. , 11. , 13. , 15. , 17. , 50. , 78. ,  0.4,
        3. , 14. , 54. , 56. , 67. , 78. , 90. ])

In [90]:
#2-D array
x=np.array([[1, 2, 4], [4, 5, 6,]])
x

array([[1, 2, 4],
       [4, 5, 6]])

In [91]:
y=np.array([[8,9,10], [11,12,13]])
y

array([[ 8,  9, 10],
       [11, 12, 13]])

In [92]:
#concatenate
z=np.concatenate((x,y), axis=0) 
z


array([[ 1,  2,  4],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [99]:
#let'e try axis=1
np.concatenate((x, y), axis=1) #this will stack in a different way.

array([[ 1,  2,  4,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [94]:
ar1=np.array([1,2])
ar1

array([1, 2])

In [95]:
ar2=np.array([[5, 6, 7], [5, 7, 8]])
ar2

array([[5, 6, 7],
       [5, 7, 8]])

In [98]:
#column_stack can stack two different dimensional arrays. 
ar3=np.column_stack((ar1,ar2))
ar3

array([[1, 5, 6, 7],
       [2, 5, 7, 8]])

In [10]:
import numpy as np
a=np.array([[[0,1,2,3],
                         [4,5,6,7]],
                         
                         [[9,10,11,12],
                          [13,14,15,16]],
                         
                         [[17,18,19,20],
                          [21,22,23,24]]])
a
                            
                            
                        

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [13]:
#let's find the number of dimensions
a.ndim #three dimensions array as after , there are two new sets. 

3

In [18]:
#number of elements
a.size

24

In [19]:
#3 mean 3-D array, 2 mean first axis, 4 mean second axis.
a.shape

(3, 2, 4)

In [35]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b=np.array([[1,3,5],
            [4,6,7],
            [4,6,8]])
b

array([[1, 3, 5],
       [4, 6, 7],
       [4, 6, 8]])

In [50]:
#reshape function
x=np.arange(10)
x
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
#reshape
np.reshape(x, newshape=(1, 10), order ='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [63]:
#let's convert 1-d array into 2-d
h=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
h.shape

(10,)

In [72]:
h1=h[np.newaxis, :] #has been converted into 2-d array.
h1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [66]:
h1.shape #we can see that now shape is 1, 9, which represent a 2-d array.

(1, 10)

In [73]:
#Let's make it column wise 2-d array.
h2=h[: , np.newaxis]
h2

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [67]:
#let's reshape this into matix.
h1.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [74]:
#slicing
h[2:7]

array([3, 4, 5, 6, 7])

In [76]:
#multiplication
h*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [77]:
#addition
h+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [78]:
#sum
h.sum()

55

In [79]:
h.mean()

5.5

In [17]:
b.ndim #that's a 2-D  array

2

In [20]:
b.size

9

In [21]:
b.shape

(3, 3)