# Multiple_Linear_Regression

- Importing the libraries

In [19]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

### 1:- Importing Data-set

In [3]:
df = pd.read_csv("salary_data.csv")
df.head()

age  distance  YearsExperience  Salary
0  31.1     77.75              1.1   39343
1  31.3     78.25              1.3   46205
2  31.5     78.75              1.5   37731
3  32.0     80.00              2.0   43525
4  32.2     80.50              2.2   39891

### 2:- Splitting Data-Set

In [4]:
a = df[['age', 'distance', 'YearsExperience']]
b = df['Salary']

In [12]:
a_train, a_test, b_train, b_test= train_test_split(a, b, test_size=0.2, random_state=0)

### 3:- Fit Linear Regression Model

In [13]:
model=LinearRegression().fit(a_train, b_train)

### 4:- Prediction of values

In [14]:
y_pred = model.predict(a_test)
y_pred

array([ 40768., 122752.,  64960.,  63104., 115200., 107776.])

- Range is the difference between the predicted value and actual value.

In [17]:
model.predict([[31.1, 77.75, 1.1]])

c:\Users\thech\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([37024.])

### 5:- Calculation of Co-Efficient and intercept

- Calculation of coefficient

In [18]:
model.coef_

array([-7.23472174e+15, -2.16813894e+14,  7.77675648e+15])

- Calculation of intercept

In [20]:
model.intercept_

2.3330269435026387e+17

### 6:- Evaulation of the model

In [22]:
r2_score(b_test, y_pred)

0.9881121259003347

In [23]:
print("Traning data Regression Score = " , model.score(a_train, b_train))
print("Testing data Regression Score = " , model.score(a_test, b_test))

Traning data Regression Score =  0.9410845579000405
Testing data Regression Score =  0.9881121259003347
